[build]
  base    = "/"
  publish = "example/dist"
  command = "yarn example expo export --platform web"
  environment = { YARN_VERSION = "3.2.2" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
